version: '3.3'

networks:
  edge:
    external: true

services:
  traefik:
    image: "traefik:2.4"
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
#      - target: 8080
#        published: 8080
#        mode: host
    networks:
      edge:
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./docker/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./docker/logs:/opt/traefik/logs"
    deploy:
      placement:
        constraints:
          - node.role == manager
        preferences:
          - spread: node.id
