global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          permanent: true

  https:
    address: :443

log:
  filePath: /opt/traefik/logs/traefik.log
  format: json

accessLog:
  filePath: /opt/traefik/logs/access-log.txt
  format: json

api:
  insecure: true
  dashboard: true

providers:
  docker:
    exposedByDefault: false
    network: edge
    swarmMode: true
